Nunana/Controllers/RentalsController.cs
using AutoMapper;
using Nunana.Extensions;
using Nunana.Persistence;
using System.Collections.Generic;
using System.Web.Mvc;
using Nunana.Core;
using Nunana.Core.Models;
using Nunana.Core.ViewModels;

namespace Nunana.Controllers
{
    [Authorize]
    public class RentalsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public RentalsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var query = new RentalQuery { IsCancelled = false };
            var rentals = _unitOfWork.Rentals.GetRentals(query);

            var viewModel = Mapper.Map<IEnumerable<Rental>, List<RentalListViewModel>>(rentals);

            return View(viewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Cancelled()
        {
            var query = new RentalQuery { IsCancelled = true };
            var cancelledRooms = _unitOfWork.Rentals.GetRentals(query);

            var viewModel = Mapper.Map<IEnumerable<Rental>, List<RentalListViewModel>>(cancelledRooms);

            return View(viewModel);
        }

        public ActionResult ExpiringThisMonth()
        {
            var firstDayOfMonth = DateTimeExtensions.CalculateFirstDayOfThisMonth();
            var lastDayOfMonth = DateTimeExtensions.CalculateLastDayOfThisMonth(firstDayOfMonth);

            var query = new RentalQuery { StartDate = firstDayOfMonth, EndDate = lastDayOfMonth };
            var expiringRentals = _unitOfWork.Rentals.GetRentals(query);

            var viewModel = Mapper.Map<IEnumerable<Rental>, List<RentalListViewModel>>(expiringRentals);

            return View(viewModel);
        }
    }
}

Nunana/Controllers/RoomsController.cs
using AutoMapper;
using Nunana.Persistence;
using System.Collections.Generic;
using System.Web.Mvc;
using Nunana.Core;
using Nunana.Core.Models;
using Nunana.Core.ViewModels;

namespace Nunana.Controllers
{
    [Authorize]
    public class RoomsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public RoomsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var rooms = _unitOfWork.Rooms.GetRooms(null);

            var viewModel = Mapper.Map<IEnumerable<Room>, List<RoomsListViewModel>>(rooms);

            return View(viewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomFormViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            var roomFromMap = Mapper.Map<RoomFormViewModel, Room>(viewModel);

            var newRoom = new Room(roomFromMap.RoomNumber, roomFromMap.Type, User.Identity.Name);

            _unitOfWork.Rooms.Add(newRoom);
            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var room = _unitOfWork.Rooms.GetRoom(id);

            if (room == null) return HttpNotFound();

            var viewModel = Mapper.Map<Room, RoomFormViewModel>(room);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RoomFormViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            var room = _unitOfWork.Rooms.GetRoom(viewModel.Id);
            if (room == null) return HttpNotFound();

            Mapper.Map(viewModel, room);

            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }

        public ActionResult Vacant()
        {
            var query = new RoomQuery { IsVacant = true };

            var vacantRooms = _unitOfWork.Rooms.GetRooms(query);

            var viewModel = Mapper.Map<IEnumerable<Room>, List<RoomsListViewModel>>(vacantRooms);

            return View(viewModel);
        }
    }
}

Nunana/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nunana</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/libcss")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nunana", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Rooms <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All Rooms", "Index", "Rooms")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Vacant", "Vacant", "Rooms")</li>
                        </ul>   
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Rentals<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("All Rentals", "Index", "Rentals")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Cancelled", "Cancelled", "Rentals")</li>
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("Expiring", "ExpiringThisMonth", "Rentals")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Tenants", "Index", "Tenants")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nunana</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>