Nunana/Controllers/TenantsController.cs
using AutoMapper;
using Nunana.Persistence;
using System.Collections.Generic;
using System.Web.Mvc;
using Nunana.Core;
using Nunana.Core.Models;
using Nunana.Core.ViewModels;

namespace Nunana.Controllers
{
    [Authorize]
    public class TenantsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TenantsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            var tenants = _unitOfWork.Tenants.GetTenants();

            var viewModel = Mapper.Map<IEnumerable<Tenant>, List<TenantsListViewModel>>(tenants);

            return View(viewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TenantFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            var tenant = Mapper.Map<TenantFormViewModel, Tenant>(viewModel);

            _unitOfWork.Tenants.Add(tenant);
            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var tenant = _unitOfWork.Tenants.GetTenant(id);
            if (tenant == null) return HttpNotFound();

            var viewModel = Mapper.Map<Tenant, TenantFormViewModel>(tenant);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TenantFormViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            var tenant = _unitOfWork.Tenants.GetTenant(viewModel.Id);
            if (tenant == null) return HttpNotFound();

            Mapper.Map(viewModel, tenant);

            _unitOfWork.Complete();

            return RedirectToAction("Index");
        }

    }

}

Nunana/Controllers/api/TenantsController.cs
using AutoMapper;
using Nunana.Persistence;
using System;
using System.Collections.Generic;
using System.Web.Http;
using Nunana.Core;
using Nunana.Core.DTOs;
using Nunana.Core.Models;

namespace Nunana.Controllers.api
{
    public class TenantsController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;

        public TenantsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IHttpActionResult GetTenants(string query = null)
        {
            var dto = new List<TenantSearchDto>();

            if (String.IsNullOrWhiteSpace(query)) return Ok(dto);

            var tenants = _unitOfWork.Tenants.GetTenantsWithName(query);
            dto = Mapper.Map<IEnumerable<Tenant>, List<TenantSearchDto>>(tenants);

            return Ok(dto);
        }
    }
}

Nunana/Views/Tenants/Create.cshtml
@model Nunana.Core.ViewModels.TenantFormViewModel

@{
    ViewBag.Title = "Add Tenant";
}
<br />
<a class="btn btn-info pull-right" href="@Url.Action("Index")"><i class="fa fa-chevron-left"></i> Back To Tenants List</a>

<h3 class="text-info">ADD NEW TENANT</h3> <br />
@using (Html.BeginForm("Create", "Tenants", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EmergencyContactFirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EmergencyContactFirstName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EmergencyContactLastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EmergencyContactLastName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EmergencyContactEmail, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EmergencyContactEmail, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EmergencyContactPhoneNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EmergencyContactPhoneNumber, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EmergencyContactAddress, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EmergencyContactAddress, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-success" value="Create Tenant">
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Nunana/Views/Tenants/Edit.cshtml
@model Nunana.Core.ViewModels.TenantFormViewModel
@{
    ViewBag.Title = "Edit";
}

<br />
<a class="btn btn-warning pull-right" href="@Url.Action("Index")"><i class="fa fa-chevron-left"></i> Back To Tenants List</a>

<h3 class="text-info">EDIT TENANT INFORMATION</h3> <br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyContactFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmergencyContactFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyContactFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyContactLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmergencyContactLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyContactLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyContactPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmergencyContactPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyContactPhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyContactAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmergencyContactAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyContactAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmergencyContactEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmergencyContactEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmergencyContactEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <a class="btn btn-warning js-cancel" href="@Url.Action("Index")"><i class="fa fa-ban">&nbsp;</i>Cancel</a>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/libs")
    <script>
        $(document).ready(function () {
            $('.js-cancel').on('click', function (e) {
                e.preventDefault();
                var link = $(e.target);
                swal({
                    title: "Leave this page?",
                    text: "Edits will not be saved",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonText: "Yes!",
                    confirmButtonClass: 'btn btn-warning',
                    cancelButtonText: "No",
                    cancelButtonClass: 'btn btn-primary'
                }).then((result) => {
                    if (result.value) {
                        window.location.replace(link.attr('href'));
                    }
                });
            });
        });
    </script>
}

Nunana/Views/Tenants/Index.cshtml
@model IEnumerable<Nunana.Core.ViewModels.TenantsListViewModel>
@{
    ViewBag.Title = "Tenants List";
}

<a class="btn btn-success" href="@Url.Action("Create")"><i class="fa fa-user">&nbsp;</i>Add New Tenant</a>

<h3 class="text-info">TENANTS LIST</h3> <br />

<table class="table table-striped table-responsive dataTable">
    <thead>
        <tr>
            <th>Name</th>
            <th>Phone Number</th>
            <th>Email</th>
            <th>Emergency Contact</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(model => item.FullName)</td>
                <td>@Html.DisplayFor(model => item.PhoneNumber)</td>
                <td>@Html.DisplayFor(model => item.Email)</td>
                <td>@Html.DisplayFor(model => item.EmergencyContactPhoneNumber)</td>
                <td>
                    <a class="btn btn-sm btn-primary" href="@Url.Action("Edit", new { id=item.Id})"><i class="fa fa-edit">&nbsp;</i>Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>


@section scripts{
    @Scripts.Render("~/bundles/libs")
    <script>
        $(document).ready(function () {
            $('.dataTable').DataTable();
        });
    </script>
}